[redis]
url="redis://127.0.0.1:6379/"

[mysql]
url="mysql://root:123456@localhost:3306/place_order"

[binance_api_config]
api_key="67WL2xnCqYBCtOsMSzmFywoSuG2QWbBBiMBKEnPRnMh4T27geTEq1eeE7fUatTz6"
secret_key="ZALhMnscTAtzMHna1CLmFDmO3hHE6To2ZNsLKfOrRj2Igs9hEg2t7px35i2b09ti"

[[ip_config]]
name="CN"
ip="192.168.1.1"
port="11"

[[ip_config]]
name="TW"
ip="192.168.2.2"
port="22"

[[ip_config]]
name="JP"
ip="192.168.3.3"
port="33"